FROM python:3.7.6

RUN echo "mnist1.2"

WORKDIR /home/

RUN git clone https://github.com/lee-JunR/FashionMnist_api

WORKDIR /home/FashionMnist_api

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN python manage.py migrate

EXPOSE 5050

